result1 = bool(1 <= 2)
result2 = bool(100 == 200)
result3 = bool("hello" != "hello")
result4 = bool(0)
result5 = bool(3.14 > 2.71)
result6 = bool("")
result7 = bool(None)
result8 = bool([1, 2, 3])
result9 = bool({})
result10 = bool(set())

print(result1)  
print(result2)  
print(result3)  
print(result4)  
print(result5)  
print(result6)  
print(result7)  
print(result8)  
print(result9)  
print(result10) 